import { MetadataRoute } from "next"
import { CITIES } from "@/data/cities"
import { BLOG_POSTS } from "@/data/blog-posts"

const BASE = "https://dmv-prep.com"
const STATES = [
  "alabama","alaska","arizona","arkansas","california","colorado","connecticut","delaware",
  "florida","georgia","hawaii","idaho","illinois","indiana","iowa","kansas","kentucky",
  "louisiana","maine","maryland","massachusetts","michigan","minnesota","mississippi",
  "missouri","montana","nebraska","nevada","new-hampshire","new-jersey","new-mexico",
  "new-york","north-carolina","north-dakota","ohio","oklahoma","oregon","pennsylvania",
  "rhode-island","south-carolina","south-dakota","tennessee","texas","utah","vermont",
  "virginia","washington","west-virginia","wisconsin","wyoming"
]
const LANGS = ["spanish","chinese","vietnamese","portuguese","haitian-creole"]
const CLUSTER = ["dmv-practice-test","road-sign-practice-test","permit-test-questions","dmv-handbook-summary","dmv-test-tips","dmv-cheat-sheet"]
const GUIDES = ["what-does-stop-sign-mean","yield-sign-meaning","right-of-way-rules","lane-markings-explained","speed-limit-sign-rules","railroad-crossing-rules","school-zone-speed-limit","no-passing-zone-meaning","how-to-pass-dmv-test"]

const QUESTION_SLUGS = [
    "what-does-a-yellow-diamond-sign-mean",
    "what-does-a-red-octagon-sign-mean",
    "what-does-a-yield-sign-mean",
    "what-does-a-flashing-red-light-mean",
    "what-does-a-flashing-yellow-light-mean",
    "what-does-a-pennant-shaped-sign-mean",
    "who-has-right-of-way-at-a-4-way-stop",
    "when-must-you-yield-to-a-pedestrian",
    "when-must-you-stop-for-a-school-bus",
    "what-is-the-speed-limit-in-a-school-zone",
    "what-is-the-speed-limit-in-a-residential-area",
    "what-is-the-minimum-speed-on-a-highway",
    "when-must-you-stop-at-a-railroad-crossing",
    "what-is-the-safe-following-distance",
    "what-is-the-bac-limit-for-driving",
    "what-are-the-rules-for-passing",
    "what-does-a-double-yellow-line-mean",
    "what-does-a-white-dashed-line-mean",
    "who-has-right-of-way-when-merging",
    "how-many-questions-on-dmv-test",
    "what-color-are-warning-signs",
    "what-color-are-regulatory-signs",
    "what-shape-is-a-warning-sign",
    "what-shape-is-a-stop-sign",
    "what-shape-is-a-yield-sign",
    "what-does-an-orange-sign-mean",
    "what-does-a-blue-sign-mean",
    "what-does-a-green-sign-mean",
    "what-does-a-brown-sign-mean",
    "what-does-a-flashing-arrow-panel-mean",
    "what-is-a-crossbuck-sign",
    "what-does-a-no-passing-zone-sign-look-like",
    "what-does-a-white-line-on-the-right-side-mean",
    "what-does-a-solid-yellow-line-mean",
    "what-is-a-center-turn-lane",
    "who-has-right-of-way-at-uncontrolled-intersection",
    "when-turning-left-who-has-right-of-way",
    "who-must-yield-in-a-roundabout",
    "must-you-yield-to-emergency-vehicles",
    "what-is-the-move-over-law",
    "when-must-you-yield-to-a-bicyclist",
    "right-of-way-at-t-intersection",
    "what-is-the-basic-speed-law",
    "when-are-speed-fines-doubled",
    "what-is-the-highway-speed-limit",
    "what-speed-should-you-drive-in-fog",
    "what-speed-should-you-drive-in-rain",
    "what-is-hydroplaning",
    "how-do-you-recover-from-a-skid",
    "what-is-defensive-driving",
    "what-are-blind-spots",
    "when-should-you-use-high-beam-headlights",
    "when-must-you-turn-on-headlights",
    "what-is-implied-consent-law",
    "what-is-dui",
    "what-happens-if-you-refuse-breathalyzer",
    "how-far-from-fire-hydrant-can-you-park",
    "how-far-from-intersection-can-you-park",
    "how-far-from-railroad-crossing-can-you-park",
    "what-is-the-proper-way-to-merge",
    "what-is-the-three-second-rule",
    "what-is-a-school-bus-safety-zone",
    "when-is-it-legal-to-pass-on-the-right",
    "what-is-the-proper-hand-position-on-steering-wheel",
    "what-should-you-do-if-your-brakes-fail",
    "what-should-you-do-if-a-tire-blows-out",
    "when-must-you-wear-a-seat-belt",
    "can-you-use-phone-while-driving",
    "what-is-road-rage",
    "what-do-yellow-pavement-markings-mean",
    "what-do-white-pavement-markings-mean",
    "what-is-a-rumble-strip",
    "what-does-a-crosswalk-marking-mean",
    "what-is-a-bike-lane-marking",
    "what-does-a-railroad-crossing-pavement-marking-mean",
    "what-does-only-painted-on-road-mean",
    "what-does-a-green-arrow-signal-mean",
    "what-does-a-yellow-arrow-signal-mean",
    "what-does-a-red-arrow-signal-mean",
    "what-is-a-pedestrian-signal",
    "what-is-a-lane-control-signal",
    "what-is-a-slow-moving-vehicle-sign",
    "what-does-a-keep-right-sign-mean",
    "what-does-a-one-way-sign-mean",
    "what-does-a-divided-highway-sign-mean",
    "who-has-right-of-way-when-backing-up",
    "who-has-right-of-way-entering-traffic",
    "right-of-way-at-private-driveway",
    "who-has-right-of-way-at-four-way-stop-simultaneous",
    "must-you-yield-to-funeral-procession",
    "what-is-the-speed-limit-in-a-business-district",
    "can-you-drive-at-the-speed-limit-in-bad-weather",
    "what-is-the-speed-limit-near-a-school",
    "what-is-the-minimum-following-distance-at-highway-speed",
    "what-is-carbon-monoxide-danger-in-car",
    "what-should-you-do-when-stopped-by-police",
    "how-do-you-park-on-a-hill-with-curb",
    "what-is-a-no-zone-around-trucks",
    "what-is-tailgating",
    "what-should-you-do-at-a-flooded-road",
    "how-do-you-signal-a-turn-by-hand",
    "how-far-in-advance-should-you-signal",
    "what-is-a-controlled-intersection",
    "what-is-a-designated-driver",
    "what-does-abs-stand-for",
    "what-is-the-danger-of-drowsy-driving",
    "what-should-you-do-in-a-collision",
    "what-is-the-open-container-law",
    "when-must-you-use-turn-signals",
    "what-is-the-proper-lane-for-turning-right",
    "what-is-the-proper-lane-for-turning-left",
    "how-do-you-make-a-three-point-turn",
    "when-can-you-make-a-u-turn",
    "what-is-double-parking",
    "what-is-the-danger-of-distracted-driving",
    "how-should-you-position-mirrors",
    "what-is-the-correct-following-distance-for-motorcycles",
    "how-do-you-drive-safely-in-construction-zones",
    "what-is-a-safety-corridor",
    "what-is-right-of-way-at-a-traffic-circle",
    "what-are-the-rules-for-school-bus-passing",
    "how-old-do-you-have-to-be-to-get-a-permit",
    "how-long-is-a-learner-permit-valid",
    "how-many-supervised-driving-hours-required",
    "what-documents-do-you-need-for-dmv-test",
    "can-you-retake-the-dmv-written-test",
    "what-is-the-dmv-test-pass-rate",
    "how-to-study-for-dmv-test",
    "what-is-a-provisional-license",
    "what-is-the-graduated-license-system",
    "what-is-a-real-id",
    "when-do-you-need-to-renew-your-license",
    "what-happens-if-you-drive-without-insurance",
    "what-is-right-turn-on-red",
    "what-is-left-turn-on-red",
    "what-is-failure-to-yield",
    "what-is-a-traffic-citation",
    "what-is-a-suspended-license",
    "what-is-reckless-driving",
    "what-is-the-right-of-way-for-blind-pedestrians",
    "what-is-a-speed-trap",
    "where-can-you-not-park",
    "what-is-parallel-parking",
    "what-does-a-yellow-curb-mean",
    "what-does-a-red-curb-mean",
    "what-does-a-white-curb-mean",
    "what-does-a-blue-curb-mean",
    "what-is-bac",
    "how-many-drinks-to-reach-bac-limit",
    "does-coffee-sober-you-up",
    "what-are-dui-penalties",
    "can-prescription-drugs-affect-driving",
    "how-to-drive-in-snow",
    "what-is-black-ice",
    "when-should-you-turn-on-hazard-lights",
    "what-to-do-if-you-miss-your-exit",
    "what-is-the-zipper-merge",
    "how-to-share-road-with-trucks",
    "how-to-share-road-with-motorcycles",
    "how-to-share-road-with-bicycles",
    "how-to-share-road-with-pedestrians",
    "what-is-an-acceleration-lane",
    "what-is-a-deceleration-lane",
    "what-is-an-hov-lane",
    "what-to-do-at-a-flashing-traffic-light",
    "what-is-a-protected-left-turn",
    "what-is-a-permissive-left-turn",
    "what-does-speed-limit-ahead-sign-mean",
    "what-does-wrong-way-sign-mean",
    "what-does-do-not-enter-sign-mean",
    "what-does-advisory-speed-sign-mean",
    "what-to-do-if-your-car-catches-fire",
    "what-to-do-if-accelerator-sticks",
    "what-to-do-if-you-drive-into-water",
    "who-has-right-of-way-emergency-vehicle-intersection",
    "does-right-of-way-mean-you-can-proceed-unsafely",
    "what-is-the-speed-limit-on-a-two-lane-highway",
    "what-is-the-speed-limit-on-an-interstate",
    "what-is-an-sr22",
    "what-is-a-points-system",
    "what-is-defensive-driving-course",
    "what-is-the-proper-tire-pressure",
    "what-is-the-minimum-tire-tread-depth",
    "how-often-should-you-check-mirrors",
    "how-far-can-high-beams-illuminate",
    "when-to-dim-headlights-for-oncoming-traffic",
    "california-dmv-test-questions",
    "florida-dmv-test-questions",
    "texas-dmv-test-questions",
    "new-york-dmv-test-questions",
    "what-does-a-t-intersection-sign-mean",
    "what-does-a-merge-sign-mean",
    "what-does-a-lane-ends-sign-mean",
    "what-does-a-winding-road-sign-mean",
    "what-does-a-sharp-curve-sign-mean",
    "what-does-a-hill-sign-mean",
    "what-does-a-low-clearance-sign-mean",
    "what-does-a-dip-sign-mean",
    "what-does-a-bump-sign-mean",
    "what-does-a-soft-shoulder-sign-mean",
    "what-does-a-narrow-bridge-sign-mean",
    "what-does-a-two-way-traffic-sign-mean",
    "what-does-a-traffic-signal-ahead-sign-mean",
    "what-does-a-stop-ahead-sign-mean",
    "what-does-a-yield-ahead-sign-mean",
    "right-of-way-blind-intersection",
    "when-must-you-yield-to-livestock",
    "what-is-the-two-second-rule",
    "what-is-a-space-cushion",
    "what-is-overdriving-headlights",
    "what-is-target-fixation",
    "what-is-velocity-in-driving",
    "what-is-perception-reaction-time",
    "what-to-do-when-headlights-fail",
    "what-is-the-correct-way-to-enter-a-roundabout",
    "what-is-the-safest-lane-on-a-highway",
    "when-can-you-legally-speed",
    "what-is-an-uncontrolled-railroad-crossing",
    "how-to-drive-safely-in-heavy-traffic",
    "what-is-a-forced-stop",
    "what-is-lane-splitting",
    "what-is-the-correct-way-to-change-lanes",
    "what-is-aggressive-driving",
    "how-to-drive-safely-near-school-buses",
    "what-is-engine-braking",
    "what-is-the-correct-speed-for-a-curve",
    "what-is-the-safest-way-to-back-up",
    "what-causes-most-car-accidents",
    "what-is-a-chevron-alignment-sign",
    "what-does-a-low-clearance-sign-mean",
    "what-does-a-rectangular-rapid-flashing-beacon-mean",
    "what-does-a-crossbuck-sign-look-like",
    "when-driving-in-heavy-traffic-you-should",
    "what-shape-is-a-school-zone-sign",
    "what-is-a-controlled-access-highway",
    "what-to-do-if-you-see-wrong-way-driver",
    "what-does-a-pedestrian-hybrid-beacon-mean",
    "what-does-a-rectangular-rapid-flashing-beacon-mean",
    "what-is-a-guide-sign",
    "what-is-a-route-marker",
    "what-is-a-mile-marker",
    "what-does-a-rest-area-sign-mean",
    "what-is-a-chevron-sign",
    "what-is-a-delineator",
    "what-is-stopping-distance",
    "how-does-rain-affect-stopping-distance",
    "what-is-a-safe-speed-for-conditions",
    "who-yields-at-a-yield-sign",
    "right-of-way-school-crosswalk",
    "right-of-way-construction-zone",
    "how-long-does-alcohol-stay-in-system",
    "what-is-zero-tolerance-for-minors",
    "what-is-drugged-driving",
    "when-are-windshield-wipers-required",
    "what-are-required-vehicle-equipment",
    "what-is-a-safety-belt-law",
    "what-to-do-at-a-power-outage-intersection",
    "how-to-drive-in-a-dust-storm",
    "what-to-do-if-you-are-run-off-the-road",
    "what-is-the-right-way-to-yield-to-a-bus",
    "what-is-a-shared-use-path",
    "what-is-a-commercial-drivers-license",
    "what-is-an-ignition-interlock-device",
    "what-is-a-learners-permit-restriction",
    "how-to-drive-safely-near-animals",
    "what-is-the-rule-for-driving-near-fire-trucks",
    "what-are-the-rules-for-driving-with-a-trailer",
    "what-is-night-driving-danger",
    "what-is-glare-from-headlights",
    "what-is-the-danger-of-overloading-vehicle",
    "how-to-handle-a-vehicle-fire",
    "what-is-the-correct-hand-signal-for-stop",
    "what-is-a-reversible-lane",
    "what-is-a-turnabout",
    "what-is-the-move-over-law-penalty",
    "what-is-the-right-way-to-enter-a-highway",
    "what-are-the-rules-for-using-horn",
    "what-is-a-controlled-railroad-crossing",
    "what-is-speed-creep",
    "what-is-a-safe-following-distance-for-trucks",
    "what-happens-if-you-leave-scene-of-accident",
    "what-is-the-rule-for-crosswalks-with-no-markings",
    "what-is-a-traffic-break",
    "what-is-meant-by-right-of-way-not-taken",
    "what-are-rumble-strips-for",
    "how-do-you-judge-safe-gap-for-merging",
    "what-is-the-rule-for-driving-in-bike-lanes",
    "what-are-the-rules-for-motorcycle-lane-position",
    "what-is-a-flagger-in-construction-zone",
    "what-is-minimum-age-to-drive-alone",
    "what-is-the-difference-between-stop-and-yield",
    "what-is-the-blood-alcohol-limit-for-commercial-drivers",
    "what-is-a-railroad-advance-warning-sign",
    "what-causes-hydroplaning",
    "what-is-the-correct-way-to-turn-at-intersection",
    "what-is-a-no-standing-zone",
    "how-to-safely-pass-a-bicycle",
    "what-is-a-pedestrian-activated-signal",
    "what-is-the-purpose-of-turn-lanes",
    "what-is-the-three-second-rule-for-following",
    "what-is-required-when-driving-in-reverse",
    "what-is-a-traffic-cone",
    "how-does-alcohol-affect-driving",
    "what-is-a-speed-zone",
    "what-to-do-when-traffic-light-is-green",
    "what-is-the-difference-between-highway-and-freeway",
    "what-does-a-hospital-sign-look-like",
    "what-does-a-deer-crossing-sign-mean",
    "what-does-a-pedestrian-crossing-sign-mean",
    "what-does-a-bicycle-crossing-sign-mean",
    "what-does-a-school-crossing-sign-look-like",
    "what-does-a-slippery-when-wet-sign-mean",
    "what-does-a-falling-rocks-sign-mean",
    "what-does-a-divided-highway-ends-sign-mean",
    "what-does-a-weight-limit-sign-mean",
    "what-does-a-no-u-turn-sign-mean",
    "what-does-a-no-left-turn-sign-mean",
    "what-does-a-no-right-turn-sign-mean",
    "what-does-a-road-narrows-sign-mean",
    "what-does-a-pavement-ends-sign-mean",
    "what-does-a-median-sign-mean",
    "right-of-way-at-alley",
    "right-of-way-pedestrian-no-crosswalk",
    "right-of-way-three-way-stop",
    "right-of-way-fire-truck-intersection",
    "right-of-way-entering-parking-lot",
    "right-of-way-bicycle-in-lane",
    "right-of-way-uphill-narrow-road",
    "right-of-way-construction-flagger",
    "right-of-way-school-crossing-guard",
    "what-is-the-speed-limit-in-a-parking-lot",
    "what-is-the-speed-limit-on-rural-roads",
    "can-you-exceed-speed-limit-to-pass",
    "what-happens-if-you-drive-too-slow",
    "what-is-a-variable-speed-limit",
    "what-is-the-two-second-rule-for-following",
    "what-is-the-safest-following-distance-in-rain",
    "what-is-the-correct-way-to-brake-on-ice",
    "what-should-you-check-before-a-long-drive",
    "how-to-drive-in-heavy-rain",
    "what-to-do-if-your-car-overheats",
    "what-to-do-after-a-minor-accident",
    "how-to-drive-safely-at-night",
    "what-is-the-danger-of-eating-while-driving",
    "how-to-adjust-your-mirrors-correctly",
    "what-is-the-correct-way-to-park-uphill",
    "what-is-the-safe-distance-from-a-truck",
    "what-is-the-proper-way-to-turn-right",
    "what-is-the-safest-lane-to-drive-in",
    "how-to-drive-safely-in-wind",
    "what-is-the-bac-limit-for-minors",
    "how-does-marijuana-affect-driving",
    "what-medications-can-affect-driving",
    "where-is-parking-prohibited",
    "what-is-angle-parking",
    "how-to-parallel-park-correctly",
    "what-is-a-tow-away-zone",
    "what-documents-must-you-carry-while-driving",
    "what-is-the-penalty-for-driving-without-a-license",
    "what-is-the-rule-for-using-hazard-lights",
    "what-is-a-stop-line",
    "what-is-a-speed-bump",
    "what-is-the-rule-for-turning-on-red",
    "can-you-pass-on-a-two-lane-road",
    "what-is-the-rule-for-school-bus-with-stop-sign",
    "what-is-the-rule-for-emergency-vehicles-parked",
    "what-is-the-rule-for-driving-in-fog",
    "what-are-the-rules-for-headlights-in-rain",
    "what-is-the-required-equipment-for-a-car",
    "what-is-the-minimum-tire-tread-depth-legal",
    "what-is-the-law-for-pedestrians-in-crosswalk",
    "what-is-the-rule-for-blind-pedestrians-cane",
    "what-is-vulnerable-road-user",
    "what-is-the-rule-for-sharing-lane-with-motorcycle",
    "why-are-motorcycles-hard-to-see",
    "what-to-do-when-driving-through-a-flood",
    "how-to-drive-safely-in-sun-glare",
    "what-is-liability-insurance",
    "what-is-uninsured-motorist-coverage",
    "what-does-a-wrong-way-sign-look-like",
    "what-does-a-yield-sign-require",
    "what-is-the-difference-between-stop-sign-and-yield-sign",
    "what-is-the-purpose-of-road-markings",
    "what-is-the-importance-of-scanning-ahead",
    "what-is-a-safe-following-distance-at-55mph",
    "what-is-the-importance-of-seat-belts",
    "what-is-the-danger-of-speeding",
    "what-is-the-golden-rule-of-driving",
    "how-to-avoid-road-rage-incidents",
    "what-is-the-right-way-to-exit-a-highway",
    "what-is-the-left-lane-for-on-a-highway",
    "what-is-the-difference-between-freeway-and-expressway",
    "what-to-do-at-unmarked-intersection",
    "what-is-the-rule-when-traffic-light-is-not-working",
    "what-does-a-flashing-yellow-arrow-mean",
    "what-is-the-meaning-of-double-white-lines",
    "what-is-the-green-lane-marking",
    "what-is-the-purpose-of-traffic-signals",
    "what-is-the-purpose-of-guardrails",
    "what-is-a-traffic-circle-vs-roundabout",
    "what-is-the-box-blocking-law",
    "what-is-the-bac-for-commercial-drivers",
    "what-is-the-rule-for-passing-a-horse",
    "what-are-the-rules-for-towing-a-trailer",
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  const e: MetadataRoute.Sitemap = []

  // Static pages
  const statics = [
    { url: "/", priority: 1.0 },
    { url: "/states", priority: 0.9 },
    { url: "/pricing", priority: 0.8 },
    { url: "/about", priority: 0.5 },
    { url: "/lessons", priority: 0.8 },
    { url: "/road-signs-practice-test", priority: 0.9 },
    { url: "/dmv-exam-simulator", priority: 0.9 },
    { url: "/permit-test-practice", priority: 0.9 },
    { url: "/dmv-cheat-sheet", priority: 0.9 },
    { url: "/florida-dmv-test-english-only", priority: 0.95 },
    { url: "/florida-dmv-test-english-only-spanish", priority: 0.9 },
    { url: "/florida-dmv-test-english-only-haitian-creole", priority: 0.9 },
    { url: "/florida-dmv-test-english-only-portuguese", priority: 0.9 },
    { url: "/how-to-pass-florida-dmv-test-in-english", priority: 0.9 },
    { url: "/dmv-test-english-only-states", priority: 0.85 },
    { url: "/how-many-questions-on-dmv-test", priority: 0.7 },
    { url: "/dmv-test-passing-score-by-state", priority: 0.7 },
    { url: "/how-to-get-a-learners-permit", priority: 0.7 },
    { url: "/dmv-faq", priority: 0.7 },
    { url: "/dmv-practice-test", priority: 0.8 },
    { url: "/dmv-written-test", priority: 0.7 },
    { url: "/permit-test-questions", priority: 0.8 },
    { url: "/regulatory-signs-test", priority: 0.7 },
    { url: "/warning-signs-test", priority: 0.7 },
    { url: "/dmv-test-for-immigrants", priority: 0.85 },
    { url: "/dmv-test-for-seniors", priority: 0.85 },
    { url: "/dmv-test-for-first-time-drivers", priority: 0.85 },
    { url: "/dmv-test-for-non-english-speakers", priority: 0.85 },
  ]
  statics.forEach(p => e.push({ url: BASE+p.url, lastModified: now, changeFrequency: "weekly", priority: p.priority }))

  // State cluster pages
  STATES.forEach(slug => {
    CLUSTER.forEach(page => e.push({
      url: BASE+"/state/"+slug+"/"+page,
      lastModified: now,
      changeFrequency: "weekly",
      priority: page === "dmv-practice-test" ? 0.9 : page === "dmv-cheat-sheet" ? 0.85 : 0.8
    }))

    // Numbered practice tests
    for (let n = 1; n <= 10; n++) {
      e.push({ url: BASE+"/state/"+slug+"/dmv-practice-test-"+n, lastModified: now, changeFrequency: "monthly", priority: 0.7 })
    }

    // Language pages
    LANGS.forEach(lang => {
      e.push({ url: BASE+"/"+slug+"-dmv-practice-test-"+lang, lastModified: now, changeFrequency: "monthly", priority: 0.6 })
    })
  })

  // City pages
  CITIES.forEach(city => {
    e.push({ url: BASE+"/city/"+city.slug, lastModified: now, changeFrequency: "monthly", priority: 0.75 })
  })

  // DMV guide articles
  GUIDES.forEach(g => e.push({ url: BASE+"/dmv-guide/"+g, lastModified: now, changeFrequency: "monthly", priority: 0.6 }))

  // Blog pages
  e.push({ url: BASE+"/blog", lastModified: now, changeFrequency: "weekly", priority: 0.85 })
  BLOG_POSTS.forEach(post => e.push({
    url: BASE+"/blog/"+post.slug,
    lastModified: new Date(post.updatedAt),
    changeFrequency: "weekly",
    priority: post.category === "english-only-policy" ? 0.9 : 0.8
  }))

  // Question answer pages
  QUESTION_SLUGS.forEach(slug => e.push({
    url: BASE+"/questions/"+slug,
    lastModified: now,
    changeFrequency: "monthly",
    priority: 0.6
  }))

  return e
}
